server:
  ip: 127.0.0.1
  port: 8080

third_party:
  url_link: http://47.112.167.85:5004 # 对接外部系统URL
log:
  level: info
  file: logs/transformer.log
  rotate: 1
  keep: 30
database:
  address: (47.112.167.85:43016)/transformer_mz?charset=utf8mb4&parseTime=True&loc=Local
  username: minzhu_dev
  password: lvxm9Fk6dldt%Wji
  debug: true
  max_idle: 4
  max_open: 4
  max_life: 60


docs:
  uploadpath: ./upload/
